[project]
name = "rural-geog-classif"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastparquet>=2026.3.0",
    "ipykernel>=7.2.0",
    "jupyter>=1.1.1",
    "label-studio-sdk>=2.0.19",
    "matplotlib>=3.10.9",
    "pandas>=3.0.2",
    "torch>=2.11.0",
    "transformers>=5.8.0",
]
